### ISSUE TITLE
环境变量相关问题 ＆ 启动过程中出现 SyntaxError: Export named 'diffieHellman' not found in module 'crypto'.

### ISSUE THREAD

**Issue by LuRenDing2020** [SMS-COSMO/the1068fm#4]
如图

**Comment by LuRenDing2020** [comment]
![捕获1](https://github.com/user-attachments/assets/20e8f7af-a880-4116-a267-e62e32b4cda0)

**Comment by ZTL-UwU** [comment]
我猜你用的是 `bun --bun dev`。如果是的话用 `bun dev` 就不会有这个问题了。https://github.com/oven-sh/bun/issues/9569

**Comment by LuRenDing2020** [comment]
OKK 但是在使用bun dev后出现了一些新的问题 如图 可能是我的步骤不太正确(
![屏幕截图 2024-09-18 221301](https://github.com/user-attachments/assets/02de7d82-ee6e-457b-96df-95c48e3b2e65)
![屏幕截图 2024-09-18 221315](https://github.com/user-attachments/assets/a2d95093-27b3-43ab-851e-2afcb011e66c)
————
另外有一个问题 修改后将其部署在学校内网是否需要授权呢（修改后会开源在Github上）

**Comment by ZTL-UwU** [comment]
> OKK 但是在使用bun dev后出现了一些新的问题 如图 可能是我的步骤不太正确

这个是没有配置环境变量。https://github.com/SMS-COSMO/the1068fm/blob/main/server/env.ts 环境变量参考这里面的。

- `DATABASE_URL` 填数据库地址，本地如果存在文件里就填 `file:xxx.sqlite`
- `DATABASE_CONNECTION_TYPE` 是本地数据库就填 `local`
- `DATABASE_AUTH_TOKEN` 本地的话填空字符串就行
- `SERVER_URL` 填服务器 url（这个是给 dev 用的，如果是部署环境填空字符串也不影响）
- 剩下的我刚刚传了一个 script，运行 `bun run auth:genKey` 然后复制到 `.env` 里面即可

> 另外有一个问题 修改后将其部署在学校内网是否需要授权呢（修改后会开源在Github上）

不需要，很高兴我们的项目能帮到您~（但是如果您乐意署上COSMO的名字那就更好了

**Comment by LuRenDing2020** [comment]
十分感谢您的解答！但过程并不是那么顺利，环境变量问题OK后遇到了来自 Nitro 的报错  ERROR  [nitro] [uncaughtException] array.map is not a function 在尝试解决但还没有定位到问题（抱歉深夜打扰）
![1c2fa080-3dff-4ddc-9b28-a8df19713cc5](https://github.com/user-attachments/assets/c0f7035a-85c0-4b88-abf4-9cfe2e1e4226)

**Comment by ZTL-UwU** [comment]
> 十分感谢您的解答！但过程并不是那么顺利，环境变量问题OK后遇到了来自 Nitro 的报错 ERROR [nitro] [uncaughtException] array.map is not a function 在尝试解决但还没有定位到问题（抱歉深夜打扰） 

看报错信息的话应该是 `DATABASE_CONNECTION_TYPE: z.enum(['remote', 'local']),` 或者是 `NODE_ENV: z.enum(['development', 'production']),` 解析有问题。

```js
if (typeof input.data !== "string") {
    const ctx = this._getOrReturnCtx(input);
    const expectedValues = this._def.values;
    addIssueToContext(ctx, {
        expected: util.joinValues(expectedValues), // 这里报错
        received: ctx.parsedType,
        code: ZodIssueCode.invalid_type,
    });
    return INVALID;
}
```

可能是你的 `DATABASE_CONNECTION_TYPE` 或者 `NODE_ENV` 填的不是字符串？

正确的应该是这样👇
```ini
DATABASE_CONNECTION_TYPE="local"
NODE_ENV="development"
```

**Comment by LuRenDing2020** [comment]
是需要全部转换成上条评论中的样式 还是只用写`DATABASE_CONNECTION_TYPE`与`NODE_ENV`？

**Comment by ZTL-UwU** [comment]
应该都是 XXX="xxx"

**Comment by LuRenDing2020** [comment]
晚好 在修改完 env.ts 后出现了新的报错 请问这是否是来自 env.ts 的问题呢
[![pAKowTI.png](https://s21.ax1x.com/2024/09/19/pAKowTI.png)](https://imgse.com/i/pAKowTI)

**Comment by ZTL-UwU** [comment]
哦，是我解释的有点不清楚。`env.ts` 是不需要修改的，和 https://github.com/SMS-COSMO/the1068fm/blob/main/server/env.ts 一样就行。环境变量应该填在主文件夹里面创建的 `.env` 文件里。比如

![image](https://github.com/user-attachments/assets/2b21e8f2-1951-495f-9f7d-1af5d3a0e14a)

里面的内容就像前面说的那样填👇

```ini
DATABASE_URL="file:local.sqlite"
DATABASE_CONNECTION_TYPE="local"
DATABASE_AUTH_TOKEN=""
NODE_ENV="development"
SERVER_URL="http://localhost:3000"

ENC_PUBLIC_KEY="xxx"
ENC_PRIVATE_KEY="xxx"
ENC_KID="xxx"
SIGN_PRIVATE_KEY="xxx"
SIGN_PUBLIC_KEY="xxx"
SIGN_KID="xxx"
```

**Comment by LuRenDing2020** [comment]
好嘟 这个问题已经解决力 但还有最后一个问题 像下图这种报错 是否是因为公钥/私钥不符合格式产生的呢
![屏幕截图 2024-09-20 210306](https://github.com/user-attachments/assets/561f8ba2-739b-4611-8662-f3f212ee608d)

**Comment by LuRenDing2020** [comment]
非常感谢！所有的问题都已经解决了，这个issue这边就先关掉了

**Comment by ZTL-UwU** [comment]
对了，如果您的服务器部署在国内，可以把这里的 `https://428a-218-19-25-63.ngrok-free.app/api/search/song` 改成 `/api/search/song`，搜索音乐会更稳定且更快。

https://github.com/SMS-COSMO/the1068fm/blob/ac3627ffa50564149a7f9233bd4c1edbb464edf6/pages/manage/review.vue#L69-L74
